on:
  push:
    branches: [main] 
  
jobs: 
  deploy:
    name: Deploy 
    runs on: ubuntu-latest  

    steps: 
      - name: Checkout the code 
        run: actions/checkout@v4 

      - name: Set up Go toolchain 
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0" 
      
      - name: Build vis script 
        run: ./scripts/buildprod.sh 